# Generated by Django 2.2.4 on 2019-08-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklando', '0002_auto_20190816_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='escolas',
            field=models.ManyToManyField(to='teklando.Escola'),
        ),
    ]
