# Generated by Django 2.2.4 on 2019-08-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklando', '0004_remove_atividade_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='atividades',
            field=models.ManyToManyField(blank=True, null=True, to='teklando.Atividade'),
        ),
    ]
