# Generated by Django 2.2.4 on 2019-08-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklando', '0005_voluntario_atividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='atividades',
            field=models.ManyToManyField(blank=True, to='teklando.Atividade'),
        ),
    ]
