# Generated by Django 2.2.4 on 2019-08-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teklando', '0006_auto_20190816_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teklando.Atividade')),
                ('escolas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teklando.Escola')),
                ('voluntarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teklando.Voluntario')),
            ],
        ),
    ]
