# Generated by Django 2.2.4 on 2019-08-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teklando', '0007_sugerido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerido',
            name='escolas',
        ),
    ]
