# Generated by Django 2.2.4 on 2019-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teklando', '0009_auto_20190818_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name=' Data de Nascimento'),
        ),
    ]
